10M payload will cause server side and client side error, even just one http call.  This is wrong issue for me to address.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMVLBVTOOC90", Request id "0HMVLBVTOOC90:00000002": An unhandled exception was thrown by the application.
      Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted by the application.
       ---> System.InvalidOperationException: Reading is already in progress.
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.TryReadInternal(ReadResult& readResult)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.OnConsumeAsync()
         --- End of inner exception stack trace ---